### ISSUE TITLE
Conversion to Python3

### ISSUE THREAD

**Issue by fire** [grandrew/taskjuggler-python#8]
Python 2 is EOL. Convert to python3 tracker.

- [ ] Convert to python3
- [ ] Publish pip

**Comment by fire** [comment]
@grandrew are you still active? Even if you're not using this, merging pull requests would help.

**Comment by grandrew** [comment]
Hey! Sure! I'll work on this during this weekend

**Comment by fire** [comment]
Ping!

**Comment by takuyozora** [comment]
Pong!

**Comment by fire** [comment]
Closing due to lack of interest.
